# Superstore Natural-Language Data Q&A Engine

## Objective

To develop a Python and Pandas-based natural-language Q&A engine that allows users to ask business questions about the Superstore dataset in simple English and receive data-driven answers based on sales, profit, customers, products, geography, and time-based analysis.

In [10]:
import pandas as pd

In [12]:
 #Load Final_Cleaned Dataset
df=pd.read_csv("superstore_Final.csv")

In [13]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Year,Month,Month_Name,Year_Month
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136,259200000000000,2017,11,November,2017-11
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820,259200000000000,2017,11,November,2017-11
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714,345600000000000,2017,6,June,2017-06
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310,604800000000000,2016,10,October,2016-10
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164,604800000000000,2016,10,October,2016-10

In [ ]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Days',
 'Year',
 'Month',
 'Month_Name',
 'Year_Month']

In [ ]:
print("Rows:",len(df))
print("Columns:",len(df.columns))

Rows: 9994
Columns: 26

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9983 non-null   float64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   float64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Shipping Days  9994 non-null   int64
 22  Year           9994 non-null   int64
 23  Month          9994 non-null   int64
 24  Month_Name     9994 non-null   object
 25  Year_Month     9994 non-null   object
dtypes: float64(5), int64(4), object(17)
memory usage: 2.0+ MB

In [ ]:
#changes dtype text to datetime:
df["Order Date"]=pd.to_datetime(df["Order Date"])
df["Ship Date"]=pd.to_datetime(df["Ship Date"])

In [ ]:
# checking null values:
df[["Order Date","Ship Date","Month"]].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
Month                  int64
dtype: object

In [ ]:
#check/handle null values:
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping Days     0
Year              0
Month             0
Month_Name        0
Year_Month        0
dtype: int64

In [ ]:
# Fill missing Postal Codes with 0
df['Postal Code'] = df['Postal Code'].fillna(0)

# Check missing values again
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

## Predefined Questions for Q&A Testing

The following predefined business questions were created to test the natural-language Q&A engine. These questions cover key areas of the Superstore dataset, including sales, profit, categories, states, customers, and overall business metrics.

In [7]:
def answer_question(question):

    question = question.lower().strip()

    # Highest sales sub-category
    if ("sub-category" in question or "sub category" in question) and "highest sales" in question:

        result = df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False)

        sub_category = result.index[0]
        sales = result.iloc[0]

        return f"{sub_category} has the highest sales with approximately {sales:,.2f} USD."


    # Highest profit sub-category
    elif ("sub-category" in question or "sub category" in question) and "highest profit" in question:

        result = df.groupby("Sub-Category")["Profit"].sum().sort_values(ascending=False)

        sub_category = result.index[0]
        profit = result.iloc[0]

        return f"{sub_category} has the highest profit with approximately {profit:,.2f} USD."


    # Highest sales category
    elif "highest sales category" in question or "category has the highest sales" in question:

        result = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

        category = result.index[0]
        sales = result.iloc[0]

        return f"{category} has the highest sales with approximately {sales:,.2f} USD."


    # Highest profit category
    elif "highest profit category" in question or "category has the highest profit" in question:

        result = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

        category = result.index[0]
        profit = result.iloc[0]

        return f"{category} has the highest profit with approximately {profit:,.2f} USD."


    # Highest sales state
    elif "highest sales state" in question or "state has the highest sales" in question:

        result = df.groupby("State")["Sales"].sum().sort_values(ascending=False)

        state = result.index[0]
        sales = result.iloc[0]

        return f"{state} has the highest sales with approximately {sales:,.2f} USD."


    # Highest profit state
    elif "highest profit state" in question or "state has the highest profit" in question:

        result = df.groupby("State")["Profit"].sum().sort_values(ascending=False)

        state = result.index[0]
        profit = result.iloc[0]

        return f"{state} has the highest profit with approximately {profit:,.2f} USD."


    # Total sales
    elif "total sales" in question:

        total_sales = df["Sales"].sum()

        return f"Total sales are approximately {total_sales:,.2f} USD."


    # Total profit
    elif "total profit" in question:

        total_profit = df["Profit"].sum()

        return f"Total profit is approximately {total_profit:,.2f} USD."


    # Total quantity
    elif "total quantity" in question or "total units" in question:

        total_quantity = df["Quantity"].sum()

        return f"Total quantity sold is {total_quantity:,.0f} units."


    # Total orders
    elif "total orders" in question or "number of orders" in question:

        total_orders = df["Order ID"].nunique()

        return f"There are {total_orders:,} unique orders."


    # Total customers
    elif "total customers" in question or "number of customers" in question:

        total_customers = df["Customer ID"].nunique()

        return f"There are {total_customers:,} unique customers."


    # Average order value
    elif "average order value" in question or "aov" in question:

        total_sales = df["Sales"].sum()
        total_orders = df["Order ID"].nunique()

        aov = total_sales / total_orders

        return f"The average order value is approximately {aov:,.2f} USD."


    # Profit margin
    elif "profit margin" in question:

        total_sales = df["Sales"].sum()
        total_profit = df["Profit"].sum()

        margin = (total_profit / total_sales) * 100

        return f"The overall profit margin is approximately {margin:.2f}%."


    # Highest sales customer
    elif "highest sales customer" in question or "customer has the highest sales" in question:

        result = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False)

        customer = result.index[0]
        sales = result.iloc[0]

        return f"{customer} has the highest sales with approximately {sales:,.2f} USD."


    # Highest profit customer
    elif "highest profit customer" in question or "customer has the highest profit" in question:

        result = df.groupby("Customer Name")["Profit"].sum().sort_values(ascending=False)

        customer = result.index[0]
        profit = result.iloc[0]

        return f"{customer} has the highest profit with approximately {profit:,.2f} USD."


    # Biggest loss-making customer
    elif "highest loss customer" in question or "biggest loss customer" in question:

        result = df.groupby("Customer Name")["Profit"].sum().sort_values()

        customer = result.index[0]
        loss = result.iloc[0]

        return f"{customer} has the highest loss of approximately {abs(loss):,.2f} USD."


    # Biggest loss-making state
    elif "highest loss state" in question or "biggest loss state" in question:

        result = df.groupby("State")["Profit"].sum().sort_values()

        state = result.index[0]
        loss = result.iloc[0]

        return f"{state} has the highest loss of approximately {abs(loss):,.2f} USD."


    # Biggest loss-making sub-category
    elif ("sub-category" in question or "sub category" in question) and (
        "highest loss" in question or "biggest loss" in question
    ):

        result = df.groupby("Sub-Category")["Profit"].sum().sort_values()

        sub_category = result.index[0]
        loss = result.iloc[0]

        return f"{sub_category} has the highest loss of approximately {abs(loss):,.2f} USD."


    # Highest sales year
    elif "highest sales year" in question or "year has the highest sales" in question:

        result = df.groupby("Year")["Sales"].sum().sort_values(ascending=False)

        year = result.index[0]
        sales = result.iloc[0]

        return f"{year} has the highest sales with approximately {sales:,.2f} USD."


    # Highest profit year
    elif "highest profit year" in question or "year has the highest profit" in question:

        result = df.groupby("Year")["Profit"].sum().sort_values(ascending=False)

        year = result.index[0]
        profit = result.iloc[0]

        return f"{year} has the highest profit with approximately {profit:,.2f} USD."


    # Highest sales month
    elif "highest sales month" in question or "month has the highest sales" in question:

        result = df.groupby("Month_Name")["Sales"].sum().sort_values(ascending=False)

        month = result.index[0]
        sales = result.iloc[0]

        return f"{month} has the highest sales with approximately {sales:,.2f} USD."


    # Highest profit month
    elif "highest profit month" in question or "month has the highest profit" in question:

        result = df.groupby("Month_Name")["Profit"].sum().sort_values(ascending=False)

        month = result.index[0]
        profit = result.iloc[0]

        return f"{month} has the highest profit with approximately {profit:,.2f} USD."


    # Highest discount category
    elif "highest discount category" in question or "category has the highest discount" in question:

        result = df.groupby("Category")["Discount"].mean().sort_values(ascending=False)

        category = result.index[0]
        discount = result.iloc[0] * 100

        return f"{category} has the highest average discount at approximately {discount:.2f}%."


    # Average shipping days
    elif "average shipping days" in question or "average shipping time" in question:

        avg_shipping = df["Shipping Days"].mean()

        return f"The average shipping time is approximately {avg_shipping:.2f} days."


    else:
        return "Sorry, I don't understand this question yet."

In [104]:
answer_question("Which sub-category has the highest sales?")
answer_question("Which sub-category has the highest profit?")
answer_question("Which category has the highest sales?")
answer_question("Which state has the highest profit?")
answer_question("What are the total sales?")
answer_question("What is the average order value?")
answer_question("Which customer has the highest profit?")

'Tamara Chand has the highest profit with approximately 8,981.32 USD.'

## Interactive Natural-Language Q&A

The Q&A engine allows users to enter business questions in natural language. The system processes the user's question, identifies the relevant analysis, and returns a data-driven answer from the Superstore dataset.

The user can continue asking questions until `exit` is entered.

In [14]:
while True:

    question = input("\nYou: ")

    if question.lower() == "exit":
        print("Thank you for using the Superstore Data Analyst.")
        break

    answer = answer_question(question)

    print("Answer:", answer)

You: which category has the highest sales?
Answer: Technology has the highest sales with approximately 836,154.03 USD.

You: which customer has highest profit?
Answer: Sorry, I don't understand this question yet.

You: which customer has the highest profit?
Answer: Tamara Chand has the highest profit with approximately 8,981.32 USD.

You: exit
Thank you for using the Superstore Data Analyst.

## Conclusion

The Superstore Natural-Language Data Q&A Engine was developed using Python and Pandas to make data analysis easier through simple natural-language questions.

The project demonstrates how predefined business questions can be processed to generate data-driven answers related to sales, profit, customers, categories, states, orders, and other key business metrics.

This project helped demonstrate practical skills in:

- Python
- Pandas
- Data Analysis
- GroupBy and Aggregation
- Natural-Language Question Processing
- Business Insights
- Interactive Data Analysis